# Generated by Django 4.2.7 on 2025-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
