# Generated by Django 4.2.7 on 2025-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
