# Generated by Django 4.2.7 on 2025-09-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messagereadreceipt'),
        ('chat', '0003_alter_chatroom_avatar_url'),
    ]

    operations = [
    ]
